export class Scholarship {
    
    constructor(
        private _adharNo?: string,
        public religion?: string,
        public communityCategory?: string,
        public fatherName?: string,
        public motherName?: string,
        public familyAnnualIncome?: string,
        public instituteName?: string,
        public presentCourse?: string,
        public presentClassYear?: string,
        public modeOfStudy?: string,
        public classStartDate?: string,
        public universityBoardName?: string,
        public previousClassCourse?: string,
        public previousPassingYear?: string,
        public previousClassPercent?: string,
        public tenthRollNo?: string,
        public tenthBoardName?: string,
        public tenthPassingYear?: string,
        public tenthPercentObtained?: string,
        public twelvthrollNo?: string,
        public twelvthBoardName?: string,
        public twelvthPassingYear?: string,
        public twelvthpercentObtained?: string,
        public admissionFee?: string,
        public tutionFee?: string,
        public otherFee?: string,
        public disability?:string,
        public disabilityType?:string,
        public percentOfDisability?:string,
        public maritalStatus?:string,
        public parentsProfession?:string,
        public state?:string,
        public district?:string,
        public blockOrTaluka?:string,
        public houseNo?:string,
        public streetNo?:string,
        public pinCode?:string,
        public scheme?:string, 


    ) {
    }
}
